name: Notify Server Repo

on:
  push:
    branches: [main]
    paths: ['src/hle_common/**']

permissions:
  contents: read

jobs:
  notify:
    runs-on: arc-runner-hle-client
    container:
      image: node:20-slim
    steps:
      - uses: peter-evans/repository-dispatch@0e0cf047c08f936c436da4399814cdb4880c8cbf
        with:
          token: ${{ secrets.HLE_PAT }}
          repository: jspanos/hle
          event-type: common-updated
