name: Notify Server Repo

on:
  push:
    branches: [main]
    paths: ['src/hle_common/**']

permissions:
  contents: read

jobs:
  notify:
    runs-on: arc-runner-hle-client
    container:
      image: node:20-slim
    steps:
      - uses: peter-evans/repository-dispatch@575996ea1a010004ee30aaa78ab293b4bfb47e8b
        with:
          token: ${{ secrets.HLE_PAT }}
          repository: jspanos/hle
          event-type: common-updated
