name: Notify Server Repo

on:
  push:
    branches: [main]
    paths: ['src/hle_common/**']

permissions:
  contents: read

jobs:
  notify:
    runs-on: arc-runner-hle-client
    container:
      image: node:20-slim
    steps:
      - uses: peter-evans/repository-dispatch@b7037b45472c64c96f5a28a8c8443a7d5a237848
        with:
          token: ${{ secrets.HLE_PAT }}
          repository: jspanos/hle
          event-type: common-updated
